feat(common):first commit
DanX3N0/frontend-rojo pull request #2
Opened 2023-07-02 18:55 UTC by Zwilson135

first commit of my project

2023-07-04 23:57 UTC, Ditmar requested changes
This pr is so big, please review your scope, I think you train to do more of the task setup in the ticket websites-001

2023-07-04 23:57 UTC, Ditmar commented on src/Theme/ThemeListP.jsx
> +
please put this code in the theme main file, only one theme can exist for the whole app. put this here 
https://github.com/DanX3N0/frontend-rojo/blob/main/src/Theme/Theme.js

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/ListProducts.jsx
> +import { Container,CssBaseline,ThemeProvider} from "@mui/material"
please use single quotes, and use and correct the indentation

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/ListProducts.jsx
> +      <Container sx={{width:'1440px',height:'1024px',background:'#E6E6E8'}}>
Don't hard code the colors use the main palette from the theme file like this. 
```
import { useTheme } from '@material-ui/core'
.
.
const theme = useTheme();
.
.
<Container sx={{width:'1440px',height:'1024px',background:theme.palette.primary.somecolor}}>
>
```

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/filter/BpCheckedIcon.tsx
> +  backgroundColor: theme.palette.primary.main,
Nice catch, this is the way to include the color, feel free to add the colors if you need inside the color palette.

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/filter/BpCheckedIcon.tsx
> +*/
remove all commented code

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/filter/DividerGroup.jsx
> +function DividerGroup(props) {
please use the definition of a function like this
const dividerGroup = () => {
}

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/filter/FilterComponent.jsx
> +import {StyledContainerFilt,StylesLayoutTitle,StyledTitleFilt,StyledGroupFilt} from "./stylesFilter"
correct the indentation and use simple quotes

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/filter/FormControlCategory.jsx
> +import { FormControl,FormLabel,FormGroup,FormControlLabel,Typography,Divider} from '@mui/material'
correct the indentation

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/filter/FormControlCategory.jsx
> +          sx={{...defaultStyleFormItem,width:'66px'}}
the better way to set up the breakpoint is using our function mq from the css 
https://github.com/DanX3N0/frontend-rojo/blob/main/src/config/mq.js

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/header/Header.jsx
> +import AvatarImage from "../../../../assets/images/avatarImage.jpg"
use simple quotes here

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/header/Header.jsx
> +import UserAvatar from "./UserAvatar"
use simple quotes here

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/header/Header.jsx
> +import SearchBar from "./SearchBar";
use simple quotes here

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/header/Header.jsx
> +import AddCard from "./AddCard"
use simple quotes here

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/header/Header.jsx
> +import {Toolbar,Box} from "@mui/material"
use simple quotes here

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/header/Header.jsx
> +import { StyledBarHeader,StylesToolbar} from "./styles"
use simple quotes here

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/icons/HomeIcon.jsx
> +        <svg width="20px" height="20px">
don't copy all svg code in html plain text. you can export the file into the assets and use it directly, like this.you can use 

```
import React from 'react';
import SvgIcon from '@material-ui/core/SvgIcon';
import { ReactComponent as ImportedSvg } from '../assets/logo.svg';

const MyComponent = () => {
  return (
    <SvgIcon component={ImportedSvg} viewBox="0 0 24 24" />
  );
};

export default MyComponent;
```

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/icons/OpinionsIcon.jsx
> +    <Icon {...props}>
read the comment above

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/icons/OrdersIcon.jsx
> +    <Icon {...props}>
read the comment above

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/icons/PromotionsIcon.jsx
> +    <Icon {...props}>
read the comment above

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/icons/SearchIcon.jsx
> +    <SvgIcon {...props} viewBox="0 0 15 15">
read the comment above

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/icons/SettingIcon.jsx
> +    <Icon {...props}>
read the comment above

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/icons/SettingIcon.jsx
> +function PromotionsIcon(props) {
use the sentence like this const PromotionsIcon = props => {
}

2023-07-04 23:57 UTC, Ditmar commented on src/ui/components/ListaProductos/logo/styles.jsx
> +import {styled} from "@mui/system"
use simple quotes

2023-07-05 22:11 UTC, Zwilson135 commented
ingeniero ya le hice las correcciones como dijo

2023-07-08 00:57 UTC, olmedo90 commented
![image](https://github.com/DanX3N0/frontend-rojo/assets/77794323/e5af49e6-5957-4f99-ac27-ed68b974b82c)

It is not according to Figma. correct the following: (image of the products, title of the selected checkboxes)

2023-07-10 12:28 UTC, olmedo90 commented
![image](https://github.com/DanX3N0/frontend-rojo/assets/77794323/6fa5264a-18c9-499e-8069-ecfc1d6c5f59)

It is according to Figma. continue with the same interest. 👍

2023-07-12 22:33 UTC, Ditmar approved these changes
approved, please rebase all your code to proceded  to merge into the master branch

2023-07-13 22:44 UTC, merged