feature(common): added new feature (WEBSITES-15)
DanX3N0/frontend-rojo pull request #4
Opened 2023-07-05 05:23 UTC by DanX3N0

added feature (WEBSITES-15)

2023-07-07 16:32 UTC, Ditmar requested changes
Really nice work Dani, but is a really minimun fix, good job

2023-07-07 16:32 UTC, Ditmar commented on .gitignore
> +yarn-error.log*
nice catch

2023-07-07 16:32 UTC, Ditmar commented on src/App.styles.js
> +      backgroundColor: '#F1F0F0',
please use the theme.palette, use the color from the palette

2023-07-07 16:32 UTC, Ditmar commented on src/Theme/Theme.js
> +  fontFamily: "AllertaStencil-Regular",
use simple quotes

2023-07-07 16:32 UTC, Ditmar commented on src/Theme/Theme.js
> +  fontStyle: "normal",
use simple quotes

2023-07-07 16:32 UTC, Ditmar commented on src/Theme/Theme.js
> +  fontFamily: "AllertaStencil-Bold",
use simple quotes

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.jsx
> +               <div className={classes.lupa}>
please use only ingles to call your vars you can use classes.magnifier

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.jsx
> +                  <img className={classes.imgAdd} src={AddClient} alt='add-client' />
rename this var to imageAdd

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.jsx
> +               <div className={classes.lupa2}>
The same here change the name of this variable to secondMagnifier

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.jsx
> +               <button className={classes.addButton2}>
the same here addButton2 isn't a good name try to find another

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.jsx
> +                  <img className={classes.imgAdd2} src={AddClient} alt='add-client' />
the same here imgAdd2 isn't a good name try to find another

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.styles.js
> +      backgroundColor: '#000000',
if you don't find this color on the palette you can create a new one

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.styles.js
> +   lupa2:{
change the name of this classes based in the comments above

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.styles.js
> +   searchForm2:{
change the name of this classes based in the comments above

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.styles.js
> +   textAreaWidth2:{
change the name of this classes based in the comments above

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.styles.js
> +   textArea2:{
change the name of this classes based in the comments above

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.styles.js
> +   addButton2:{
change the name of this classes based in the comments above

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/AddAndSearch.styles.js
> +      backgroundColor: '#000000',
use the palette color

2023-07-07 16:32 UTC, Ditmar commented on src/ui/components/listClients/FilterBar.jsx
> +   const data = {
put this data in a mock file you can create a new folder   inside de src, called mockedData, please set the data there

2023-07-07 19:16 UTC, olmedo90 commented
![image](https://github.com/DanX3N0/frontend-rojo/assets/77794323/658c6d04-58cc-4cc5-abda-80d6bbe7f5b8)

no es acorde al figma corrija el color del titulo

2023-07-08 05:10 UTC, olmedo90 commented
![image](https://github.com/DanX3N0/frontend-rojo/assets/77794323/837a34d5-8648-4edf-956e-5d5fe7b44088)

It is not according to Figma. correct the following: (color of the selected checkboxes, bold text of the selected checkbox, color of the price range bar)

2023-07-08 23:05 UTC, olmedo90 commented
![image](https://github.com/DanX3N0/frontend-rojo/assets/77794323/8ce0748f-a77a-4db3-a4bf-354afc5a908c)

It is according to Figma. continue with the same interest.👍

2023-07-12 22:28 UTC, Ditmar approved these changes
approved

2023-07-12 22:29 UTC, merged