feature(common): my first commit [WEBSITES-3]
DanX3N0/frontend-rojo pull request #5
Opened 2023-07-06 18:59 UTC by coyo97

## sumary
updated the readme

2023-07-07 18:11 UTC, Ditmar requested changes
You need to use the english as a standar in all your code

2023-07-07 18:11 UTC, Ditmar commented on src/App.js
> +import FormClient from "./ui/components/formClient/FormClient";
please use simple quotes here

2023-07-07 18:11 UTC, Ditmar commented on src/App.js
> +import FormDirect from "./ui/components/formClient/FormDirect";
please use simple quotes here

2023-07-07 18:11 UTC, Ditmar commented on src/App.js
> +import FormFact from "./ui/components/formClient/FormFact";
please use simple quotes here

2023-07-07 18:11 UTC, Ditmar commented on src/ui/components/formClient/FormClient.jsx
> +  };
All this function can be improve to this way
```
const validateForm = () => {
  // Realizar la validación del formulario
  let errors = {};

  // Mapa con los nombres de los campos y sus mensajes de error correspondientes
  const fieldNames = {
    id: "El ID es obligatorio.",
    nombre: "El nombre es obligatorio.",
    apellido: "El apellido es obligatorio.",
    email: "El correo electrónico es obligatorio.",
    telefono: "El número de teléfono es obligatorio."
  };

  // Validar los campos obligatorios
  Object.keys(fieldNames).forEach(key => {
    if (!cliente[key]) {
      errors[key] = fieldNames[key];
    }
  });

  // Validar el formato del correo electrónico
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (cliente.email && !emailRegex.test(cliente.email)) {
    errors.email = "El correo electrónico no es válido.";
  }
  return errors;
};
```

2023-07-07 18:11 UTC, Ditmar commented on src/ui/components/formClient/FormDirect.jsx
> +    } else {
remove the comment

2023-07-07 18:11 UTC, Ditmar commented on src/ui/components/formClient/FormDirect.jsx
> +      console.log(envio);
remove the console log, and use only english 'envio*'

2023-07-07 18:11 UTC, Ditmar commented on src/ui/components/formClient/FormDirect.jsx
> +  const handleEtiquetaSeleccionada = (etiqueta) => {
use only english

2023-07-07 18:11 UTC, Ditmar commented on src/ui/components/formClient/formDireEnv.style.js
> +    border: "1px solid #000",
all colors must be used from the color palette

2023-07-07 18:11 UTC, Ditmar commented on src/ui/components/formClient/formFact.style.js
> +    border: "2px solid #ccc", // Añade un borde alrededor de los inputs
remove the comments of the pr, and use the colors from the palette

2023-07-08 00:09 UTC, olmedo90 commented
![image](https://github.com/DanX3N0/frontend-rojo/assets/77794323/acb12d95-cc07-4e6e-a73c-743449906cd3)

It is not according to Figma. correct the following: (position of the titles, color of components, name of the inputs, border of the buttons)

2023-07-09 00:17 UTC, olmedo90 commented
![image](https://github.com/DanX3N0/frontend-rojo/assets/77794323/0acae59f-cf40-4851-9e4e-5dbfdc7fcc85)

It is according to Figma. continue with the same interest.👍

2023-07-14 00:42 UTC, Ditmar approved these changes
approved

2023-07-14 02:51 UTC, merged